name: Dojo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dojo-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: composer install
    - name: Execute tests PHPUnit
      run: ./vendor/bin/phpunit
